export const dummyCity = [
    {
        id: 0,
        val: 'seoul',
        city: '서울',
        place: '서울',
    },
    {
        id: 1,
        val: 'busan',
        city: '부산',
        place: '부산',
    },
    {
        id: 2,
        val: 'gangneung',
        city: '강릉·속초',
        place: '강릉, 속초, 양양',
    },
    {
        id: 3,
        val: 'gapyeong',
        city: '가평·양평',
        place: '가평, 양평',
    },
    {
        id: 4,
        val: 'incheon',
        city: '인천',
        place: '인천, 강화도',
    },
    {
        id: 5,
        val: 'gyeongju',
        city: '경주',
        place: '경주',
    },
    {
        id: 6,
        val: 'jeju',
        city: '제주',
        place: '제주, 서귀포',
    },
    {
        id: 7,
        val: 'taean',
        city: '태안',
        place: '태안',
    },
    {
        id: 8,
        val: 'cheongju',
        city: '청주',
        place: '청주',
    },
    {
        id: 9,
        val: 'naju',
        city: '나주',
        place: '나주',
    },
    {
        id: 10,
        val: 'gwangju',
        city: '광주',
        place: '광주',
    },
    {
        id: 11,
        val: 'miryang',
        city: '밀양',
        place: '밀양',
    },
    {
        id: 12,
        val: 'suwon',
        city: '수원',
        place: '수원',
    },
    {
        id: 13,
        val: 'cheonan',
        city: '천안',
        place: '천안, 아산',
    },
    {
        id: 14,
        val: 'pohang',
        city: '포항',
        place: '포항',
    },
    {
        id: 15,
        val: 'ulsan',
        city: '울산',
        place: '울산',
    },
    {
        id: 16,
        val: 'daejeon',
        city: '대전',
        place: '대전',
    },
    {
        id: 17,
        val: 'daegu',
        city: '대구',
        place: '대구',
    },
]